apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /datadrive/mqc
